language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t bernardobfg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bernardobfg/docker-react npm run test